"""S14: final timemap of the edited programme, taken from the montage EDL - every text material counts from it.

edl/edl.json pieces[] = {src, t0, t1 (source seconds), from, to (frames)} -> segments {source, src_in, src_out, edit_in}
with edit_in = from / fps. A recorder-only source (edl_config extra_sources, e.g. "intro") is renamed to its
timeline.json key (e.g. "intro_plaud" - the clock of its words file). The teaser (repeated fragments of the body) is
NOT included: its words stay at their place in the body. The chapter list (edl/chapters.json) is copied in, so the
transcript, the summary and the RuTube timecodes share ONE set of chapters.
A piece whose frame length differs from its source length by > 0.08 s stops the build (a speed change is not a cut).

usage: python build_final_timemap.py --job job.json      -> materials/final_timemap.json
"""
import json
import os
import sys
from pathlib import Path

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), '..'))
from job import load  # noqa: E402

J = load()


def main():
    edl_p = Path(J.p('edl/edl.json'))
    edl = json.loads(edl_p.read_text(encoding='utf-8'))
    cfg = J.data('edl/edl_config.json', {})
    ren = {src: spec.get('timeline_key', src) for src, spec in (cfg.get('extra_sources') or {}).items()}
    fps = edl['fps']
    segs = []
    for p in edl['pieces']:
        dur_frames = p['to'] - p['from']
        dur_src = p['t1'] - p['t0']
        if abs(dur_frames / fps - dur_src) > 0.08:
            sys.exit(f'piece length mismatch (speed change?): {p}')
        segs.append({'source': ren.get(p['src'], p['src']), 'src_in': p['t0'], 'src_out': p['t1'], 'edit_in': round(p['from'] / fps, 3)})
    total = edl['durationInFrames'] / fps
    chapters = json.loads(Path(J.p('edl/chapters.json')).read_text(encoding='utf-8'))
    out = {
        '$note': 'generated by scripts/webinar/deliver/build_final_timemap.py from edl/edl.json pieces (teaser excluded)',
        'edl_mtime': edl_p.stat().st_mtime,
        'fps': fps, 'duration_s': round(total, 2),
        'teaser_s': round(edl['pieces'][0]['from'] / fps, 2) if edl.get('pieces') else 0.0,
        'segments': segs,
        'chapters': chapters,
    }
    dst = Path(J.p('materials/final_timemap.json'))
    dst.parent.mkdir(parents=True, exist_ok=True)
    with open(dst, 'w', encoding='utf-8', newline='\n') as f:
        json.dump(out, f, ensure_ascii=False, indent=1)
    print(f'{len(segs)} segments, duration {total:.2f}s, {len(chapters)} chapters -> {dst}')


if __name__ == '__main__':
    main()
